### ISSUE TITLE
GA primary map tool

### ISSUE THREAD

**Issue by rootsmusic** [AllVotingIsLocal/AllVotingIsLocal.github.io#2]
Unlike an ArcGIS map, your map doesn't show a image preview when linked in a Facebook post.  The Democracy Labs blogged about the ArcGIS map that they created for the same purpose at https://mailchi.mp/thedemlabs/georgiadropboxes

**Comment by AllVotingIsLocal** [comment]
Thanks for that flag - we're looking to find a solution for image preview now.
