### ISSUE TITLE
GA-Absentee-Ballots.html

### ISSUE THREAD

**Issue by rootsmusic** [AllVotingIsLocal/AllVotingIsLocal.github.io#3]
First, this page's tab is titled "GA-Absentee-Ballots.utf8".  Second, this page doesn't show any image preview when linked in a Facebook post.  Third, "registered voters" should be clarified whether it's including active and inactive statuses.

Can its data be segmented into registered Republicans, Democrats, other parties and non-affiliated?  Due to their leader's opposition against absentee ballots, Republican voters will have a lower request rate because they prefer to vote in-person.  Even the voting proportion of registered parties (not specific to absentee ballots) would add context to the data.

**Comment by AllVotingIsLocal** [comment]
We are a non-partisan shop and do not look at data by party or affiliation. We chose to show voters of active and inactive status rather than separate them.
